// The Blueprint — 10 Year Roadmap
// Each leaf bullet has a stable id used as DB key.

export type Item = { id: string; label: string };
export type SubSection = { id: string; title: string; items: Item[] };
export type Section = { id: string; title: string; subs: SubSection[] };
export type Category = {
  slug: string;
  number: string;
  kind: "career" | "skill";
  title: string;
  short: string;
  intro: string;
  sections: Section[];
};

const c = (slug: string, number: string, kind: "career" | "skill", title: string, short: string, intro: string, sections: Section[]): Category => ({
  slug, number, kind, title, short, intro, sections,
});

// Helper: build sub with auto ids
const sub = (catSlug: string, secNum: string, subNum: string, title: string, items: string[]): SubSection => ({
  id: `${catSlug}.${secNum}.${subNum}`,
  title,
  items: items.map((label, i) => ({
    id: `${catSlug}.${secNum}.${subNum}.${i + 1}`,
    label,
  })),
});

const sec = (id: string, title: string, subs: SubSection[]): Section => ({ id, title, subs });

// ============ CAREER 1: DATA SCIENCE ============
const dataScience = c(
  "data-science",
  "Career 1",
  "career",
  "Data Science, Analysis, Research & Development",
  "Anchor career — systematize into premium consultancy.",
  "Your anchor career — the one you already have. The goal is to systematize it into a consultancy, expand your technical range, and position yourself as a premium expert. Every sub-skill compounds your market rate and opens doors across all three careers.",
  [
    sec("1.1", "Foundations of Data Science", [
      sub("data-science", "1.1", "1", "Mathematics & Statistics", [
        "Linear Algebra: Vectors, matrices, matrix multiplication",
        "Linear Algebra: Eigenvalues and eigenvectors",
        "Linear Algebra: Singular Value Decomposition (SVD)",
        "Linear Algebra: Applications in machine learning models",
        "Calculus: Differentiation and integration",
        "Calculus: Partial derivatives",
        "Calculus: Gradient descent and optimization",
        "Probability: Bayesian vs frequentist probability",
        "Probability: Conditional probability",
        "Probability: Distributions (Normal, Binomial, Poisson)",
        "Probability: Bayes' theorem and applications",
        "Inference: Hypothesis testing (t-tests, chi-square, ANOVA)",
        "Inference: p-values and confidence intervals",
        "Inference: A/B testing design and analysis",
        "Inference: Statistical power and sample size",
        "Inference: Type I and Type II errors",
        "Regression: Simple and multiple linear regression",
        "Regression: Logistic regression",
        "Regression: Ridge, Lasso, Elastic Net regularization",
        "Regression: Polynomial regression",
      ]),
      sub("data-science", "1.1", "2", "Programming Languages", [
        "Python: Core (data types, loops, functions, OOP, error handling)",
        "Python: NumPy — numerical computing",
        "Python: Pandas — data manipulation, cleaning, aggregation",
        "Python: Matplotlib & Seaborn",
        "Python: Plotly & Dash",
        "Python: Scikit-learn",
        "Python: TensorFlow / Keras",
        "Python: PyTorch",
        "R: Tidyverse (dplyr, ggplot2, tidyr)",
        "R: Statistical modeling",
        "R: R Markdown for reporting",
        "SQL: Window functions, CTEs, subqueries",
        "SQL: Query optimization and indexing",
        "SQL: PostgreSQL, MySQL, BigQuery",
        "NoSQL: MongoDB basics",
        "JS/TS: Node.js backend",
        "JS/TS: React for data dashboards",
        "JS/TS: D3.js for custom visualizations",
      ]),
      sub("data-science", "1.1", "3", "Data Engineering", [
        "ETL vs ELT architectures",
        "Apache Airflow workflow orchestration",
        "dbt for transformation",
        "Apache Spark and PySpark",
        "Hadoop ecosystem basics",
        "Kafka for real-time streaming",
        "AWS: S3, EC2, RDS, SageMaker, Lambda",
        "GCP: BigQuery, Vertex AI, Cloud Run",
        "Azure: ML, Synapse, Data Factory",
        "Snowflake / Redshift / BigQuery architectures",
        "Star and snowflake schema design",
        "Data lake vs warehouse vs lakehouse",
      ]),
    ]),
    sec("1.2", "Machine Learning & AI", [
      sub("data-science", "1.2", "1", "Supervised Learning", [
        "Decision Trees and Random Forests",
        "Gradient Boosting: XGBoost, LightGBM, CatBoost",
        "Support Vector Machines (SVM)",
        "K-Nearest Neighbors (KNN)",
        "Naive Bayes",
        "Time series regression",
        "Cross-validation strategies",
        "Confusion matrices, ROC-AUC, precision-recall",
        "RMSE, MAE, R-squared",
        "Overfitting, underfitting, bias-variance tradeoff",
      ]),
      sub("data-science", "1.2", "2", "Unsupervised Learning", [
        "K-Means, DBSCAN, Hierarchical clustering",
        "Gaussian Mixture Models",
        "PCA (Principal Component Analysis)",
        "t-SNE, UMAP",
        "Autoencoders",
        "Isolation Forest",
        "One-class SVM",
        "Fraud detection / system monitoring applications",
      ]),
      sub("data-science", "1.2", "3", "Deep Learning & Neural Networks", [
        "Perceptrons, activation functions",
        "Backpropagation and gradient descent variants",
        "Batch normalization, dropout, regularization",
        "CNNs: Image classification and object detection",
        "Transfer learning with pretrained models",
        "RNN/LSTM/GRU sequence modeling",
        "NLP applications",
        "Attention mechanism",
        "BERT, GPT architecture",
        "Fine-tuning and prompt engineering",
        "RAG (Retrieval Augmented Generation)",
        "Building AI-powered applications",
      ]),
      sub("data-science", "1.2", "4", "MLOps", [
        "REST API deployment with FastAPI/Flask",
        "Containerization with Docker",
        "Kubernetes for scaling ML services",
        "Data drift / concept drift detection",
        "Model performance monitoring",
        "Retraining pipelines",
        "MLflow for experiment management",
        "Weights & Biases (W&B)",
        "DVC (Data Version Control)",
      ]),
    ]),
    sec("1.3", "Data Analysis & BI", [
      sub("data-science", "1.3", "1", "Exploratory Data Analysis", [
        "Data profiling and quality assessment",
        "Univariate, bivariate, multivariate analysis",
        "Missing value strategies",
        "Outlier detection and treatment",
        "Feature engineering and selection",
      ]),
      sub("data-science", "1.3", "2", "BI Tools", [
        "Power BI: DAX modeling",
        "Power BI: Power Query",
        "Power BI: Dashboard design and publishing",
        "Tableau: Calculated fields and LOD",
        "Tableau: Interactive dashboards",
        "Tableau Server / Online",
        "Google Looker Studio: Google ecosystem",
        "Looker Studio: Blended data sources",
      ]),
      sub("data-science", "1.3", "3", "Financial Data Analysis", [
        "Financial statement analysis (P&L, BS, CF)",
        "Time series analysis for financial data",
        "Portfolio analysis and risk metrics",
        "Monte Carlo simulations",
        "Quant finance fundamentals",
      ]),
    ]),
    sec("1.4", "Research Skills", [
      sub("data-science", "1.4", "1", "Research Methodology", [
        "Quantitative research design",
        "Qualitative research methods",
        "Mixed methods research",
        "Literature review and systematic reviews",
        "Research ethics and data privacy",
      ]),
      sub("data-science", "1.4", "2", "Academic & Industry Research", [
        "Reading and interpreting research papers",
        "Replicating research studies",
        "Publishing research findings",
        "Conference presentations",
        "Grant writing basics",
      ]),
    ]),
    sec("1.5", "Software Development", [
      sub("data-science", "1.5", "1", "Engineering Principles", [
        "SOLID principles",
        "Design patterns (MVC, Factory, Observer)",
        "Clean code practices",
        "Test-driven development (TDD)",
        "Agile and Scrum",
      ]),
      sub("data-science", "1.5", "2", "Backend Development", [
        "API design and REST principles",
        "GraphQL",
        "Authentication and authorization (JWT, OAuth)",
        "Database design and optimization",
        "Microservices architecture",
        "Message queues: RabbitMQ, Redis",
      ]),
      sub("data-science", "1.5", "3", "DevOps & Infrastructure", [
        "Git and version control best practices",
        "CI/CD (GitHub Actions, Jenkins)",
        "Infrastructure as Code (Terraform)",
        "Linux administration",
        "Networking fundamentals",
      ]),
    ]),
    sec("1.6", "Consulting & Freelancing", [
      sub("data-science", "1.6", "1", "Building a Consulting Practice", [
        "Defining your niche and positioning",
        "Building a portfolio and case studies",
        "Pricing services (hourly, project, retainer)",
        "Writing proposals and SOWs",
        "Client onboarding and management",
        "Deliverables and reporting standards",
      ]),
      sub("data-science", "1.6", "2", "International Client Acquisition", [
        "Upwork profile optimization",
        "Toptal application and vetting",
        "LinkedIn B2B outreach strategy",
        "Cold email copywriting for tech consulting",
        "Building referral networks",
      ]),
      sub("data-science", "1.6", "3", "Certifications", [
        "Google Professional Data Engineer",
        "AWS Certified ML Specialty",
        "Microsoft Azure Data Scientist Associate",
        "Databricks Certified Associate Developer (Spark)",
        "Coursera / DeepLearning.AI specializations",
      ]),
    ]),
  ]
);

// ============ CAREER 2: REAL ESTATE ============
const realEstate = c(
  "real-estate",
  "Career 2",
  "career",
  "Real Estate Agent & Investor",
  "Long-game wealth builder. Agent → investor.",
  "Real estate is your long-game wealth builder. Start as a licensed agent (earning commissions), then transition into investing as capital grows. In Kenya, the agent career and investor track reinforce each other — agents see deals first.",
  [
    sec("2.1", "Real Estate Fundamentals", [
      sub("real-estate", "2.1", "1", "How Markets Work", [
        "Supply and demand dynamics",
        "Property market cycles",
        "Interest rates and mortgage availability",
        "Inflation and purchasing power",
        "GDP growth and employment rates",
        "Population growth and urbanization",
        "Nairobi submarkets: Westlands, Karen, Kilimani, Lavington, Kileleshwa",
        "Satellite towns: Kitengela, Ruiru, Rongai, Juja, Thika, Ngong",
        "Coast market: Mombasa, Diani, Malindi",
        "Emerging: Kisumu, Nakuru, Eldoret",
      ]),
      sub("real-estate", "2.1", "2", "Property Types", [
        "Residential: bungalows, maisonettes, villas",
        "Apartments: bedsitters, 1BR, 2BR, 3BR, penthouses",
        "Townhouses and gated communities",
        "Student housing",
        "Commercial: Office (Grade A/B/C)",
        "Commercial: Retail — malls, shopping centers",
        "Mixed-use developments",
        "Industrial: warehousing and logistics",
        "Industrial: manufacturing space",
        "Industrial: cold storage",
        "Land: agricultural",
        "Land: residential plots",
        "Land: commercial plots",
        "Land banking strategies",
      ]),
    ]),
    sec("2.2", "Legal & Regulatory Framework", [
      sub("real-estate", "2.2", "1", "Kenya Land Law", [
        "Land Act 2012",
        "Land Registration Act 2012",
        "National Land Commission Act 2012",
        "Community Land Act 2016",
        "Freehold (absolute ownership)",
        "Leasehold (99-year leases)",
        "Communal land tenure",
        "Public land",
      ]),
      sub("real-estate", "2.2", "2", "Title Deeds & Documentation", [
        "Absolute Title",
        "Qualified Title",
        "Possessory Title",
        "Good Leasehold Title",
        "Title search at Land Registry",
        "Detecting fraudulent titles",
        "Title transfer process",
        "Mutation and subdivision",
        "Change of user applications",
      ]),
      sub("real-estate", "2.2", "3", "Real Estate Contracts", [
        "Agreement for Sale structure and clauses",
        "Offer letters and acceptance",
        "Deposit and completion payment terms",
        "Conditions precedent",
        "Breach of contract remedies",
        "Caveat emptor vs vendor disclosure",
        "Residential tenancy terms",
        "Commercial lease structures",
        "Rent escalation clauses",
        "Break clauses and exit provisions",
      ]),
      sub("real-estate", "2.2", "4", "Licensing & Professional Bodies", [
        "EARB: eligibility for registration",
        "EARB: application process and fees",
        "EARB: annual renewal",
        "EARB: code of conduct",
        "Institution of Surveyors of Kenya (ISK)",
        "Kenya Property Developers Association (KPDA)",
        "Affordable Housing Board requirements",
      ]),
    ]),
    sec("2.3", "Agency Skills & Practice", [
      sub("real-estate", "2.3", "1", "Property Valuation", [
        "Comparable Sales Method (CSM)",
        "Income Capitalization Approach",
        "Cost Approach",
        "Residual / Development Approach",
        "Location factors",
        "Infrastructure and accessibility",
        "Amenities and social infrastructure",
        "Condition and age of property",
        "Planning and zoning regulations",
        "Conducting a CMA",
        "Common valuation errors",
      ]),
      sub("real-estate", "2.3", "2", "Property Marketing", [
        "Photography and videography for listings",
        "Drone footage",
        "Virtual tours / 3D walkthroughs",
        "Listing copywriting",
        "BuyRentKenya, Jumia House, PigiaMe listings",
        "Facebook and Instagram property ads",
        "WhatsApp broadcast lists",
        "Google Ads for real estate keywords",
        "Agent brand on social media",
        "Email marketing to investor databases",
        "Open house events",
      ]),
      sub("real-estate", "2.3", "3", "Client Management", [
        "Buyer: understanding needs and budget",
        "Buyer: shortlisting and viewings",
        "Buyer: offer prep and negotiation",
        "Seller: listing agreements / exclusivity",
        "Seller: pricing strategy",
        "Seller: managing expectations",
        "Investor: portfolio tracking",
        "Investor: ROI reporting",
        "CRM: HubSpot, Zoho",
        "Lead tracking and follow-up sequences",
      ]),
      sub("real-estate", "2.3", "4", "The Transaction Process", [
        "Lead qualification",
        "Property viewing and inspection",
        "Offer and counter-offer",
        "Title search and verification",
        "Rates and rent clearance certificates",
        "Survey plans verification",
        "Land control board consents",
        "Conveyancing process",
        "Completion and handover",
        "Post-sale follow-up",
      ]),
    ]),
    sec("2.4", "Property Investment", [
      sub("real-estate", "2.4", "1", "Investment Strategies", [
        "Buy & Hold: gross / net yield",
        "Buy & Hold: cap rate",
        "Buy & Hold: cash-on-cash return",
        "Property management vs self-management",
        "Airbnb arbitrage",
        "Furnishing and staging",
        "STR pricing and occupancy",
        "STR regulatory requirements in Kenya",
        "Fix & Flip: identifying undervalued properties",
        "Fix & Flip: renovation budgeting",
        "Fix & Flip: ARV calculations",
        "Land Banking: high-growth corridors",
        "Land Banking: infrastructure pipeline research",
        "Land Banking: subdivision and resale",
        "Off-Plan: developer due diligence",
        "Off-Plan: completion risk",
        "Off-Plan: contract clauses to negotiate",
      ]),
      sub("real-estate", "2.4", "2", "Financial Analysis", [
        "Real estate pro forma",
        "Loan amortization schedules",
        "DSCR (Debt Service Coverage Ratio)",
        "IRR (Internal Rate of Return)",
        "NPV (Net Present Value)",
        "Break-even analysis",
        "Sensitivity analysis",
        "Rental income tax",
        "Capital gains tax",
        "Stamp duty rates",
        "VAT on commercial property",
      ]),
      sub("real-estate", "2.4", "3", "Property Finance", [
        "KCB, Equity, Stanbic, HF Group mortgages",
        "Kenya Mortgage Refinance Company (KMRC)",
        "Affordable Housing Scheme financing",
        "Mortgage structuring and negotiation",
        "Developer financing options",
        "Saccos and cooperative financing",
        "Joint venture structuring",
      ]),
      sub("real-estate", "2.4", "4", "Property Management", [
        "Tenant screening and selection",
        "Lease administration",
        "Rent collection systems",
        "Maintenance management",
        "Handling tenant disputes",
        "Eviction process in Kenya",
        "Building a property management team",
        "Buildium, AppFolio, local alternatives",
      ]),
    ]),
    sec("2.5", "Real Estate Technology", [
      sub("real-estate", "2.5", "1", "PropTech Tools", [
        "GIS mapping (QGIS, ArcGIS)",
        "Property data analytics platforms",
        "AVMs — how they work",
        "Blockchain / title tokenization",
        "Virtual reality property tours",
      ]),
      sub("real-estate", "2.5", "2", "Your Data Edge", [
        "Property price prediction model for Nairobi",
        "Mapping infrastructure to price appreciation",
        "Rental yield heat maps by neighborhood",
        "Lead scoring models for agents",
        "Automated market reports for investors",
      ]),
    ]),
  ]
);

// ============ CAREER 3: TRADING ============
const trading = c(
  "trading",
  "Career 3",
  "career",
  "Trading (Forex & Equities)",
  "Most intellectually demanding. Decade-long craft.",
  "The most intellectually demanding of your three careers. Rewards analytical thinking, emotional discipline, and pattern recognition. Expect years of losses and learning before consistent profitability. Treat it as a decade-long craft.",
  [
    sec("3.1", "Financial Markets Fundamentals", [
      sub("trading", "3.1", "1", "How Markets Work", [
        "Market participants",
        "Market microstructure: order books, bid-ask, liquidity",
        "How prices are determined",
        "Sessions: Sydney, Tokyo, London, New York",
        "Forex vs Stocks vs Futures vs Options",
        "Market makers vs ECN vs STP brokers",
        "Regulation: CMA Kenya, FCA UK, SEC, CFTC",
      ]),
      sub("trading", "3.1", "2", "Forex Market", [
        "Currency pairs: majors, minors, exotics",
        "Exchange rate determination",
        "Pip, lot size, leverage",
        "Rollover and swap rates",
        "Forex participants",
        "Central bank interventions",
        "KES pairs dynamics",
      ]),
      sub("trading", "3.1", "3", "Equities Market", [
        "How stock exchanges work",
        "NSE structure",
        "How to read a stock quote",
        "NSE 20, NASI, NSE 25 indices",
        "NYSE, NASDAQ, LSE",
        "IPOs, rights issues, corporate actions",
        "Dividends and stock splits",
      ]),
      sub("trading", "3.1", "4", "Other Markets", [
        "Futures markets",
        "Options (calls, puts, basic strategies)",
        "Commodities: oil, gold, agricultural",
        "Cryptocurrencies as tradeable asset",
        "ETFs and index trading",
      ]),
    ]),
    sec("3.2", "Technical Analysis", [
      sub("trading", "3.2", "1", "Charts & Timeframes", [
        "Candlestick charts — anatomy",
        "Bar charts and line charts",
        "Timeframes: M1 → MN",
        "Multi-timeframe (top-down) analysis",
      ]),
      sub("trading", "3.2", "2", "Price Action", [
        "Support and resistance",
        "Trendlines and channels",
        "Market structure (HH, HL, LH, LL)",
        "Break of structure / change of character",
        "Order blocks / institutional footprints",
        "Fair value gaps (FVG)",
        "Liquidity pools (BSL/SSL)",
        "Single candles: Doji, Hammer, Shooting Star, Marubozu, Spinning Top",
        "Two-candle: Engulfing, Harami, Tweezers",
        "Three-candle: Morning/Evening Star, Three Soldiers/Crows",
      ]),
      sub("trading", "3.2", "3", "Indicators", [
        "Moving Averages: SMA, EMA, WMA",
        "MACD",
        "ADX",
        "Parabolic SAR",
        "RSI",
        "Stochastic Oscillator",
        "CCI",
        "Williams %R",
        "OBV",
        "Volume Profile",
        "Accumulation/Distribution Line",
        "Bollinger Bands",
        "ATR",
        "Keltner Channels",
        "Fibonacci retracement levels",
        "Fibonacci extensions",
        "Fibonacci confluence zones",
      ]),
      sub("trading", "3.2", "4", "Advanced Concepts", [
        "Elliott Wave: impulse waves",
        "Elliott Wave: corrective waves",
        "Elliott Wave: counting rules",
        "Harmonic: Gartley, Bat, Butterfly, Crab, Shark",
        "ABCD pattern",
        "Wyckoff: accumulation/distribution",
        "Wyckoff events: spring, upthrust, SOW",
        "Wyckoff: Composite Man",
        "SMC: institutional order flow",
        "SMC: breaker blocks",
        "SMC: mitigation blocks",
        "SMC: premium / discount zones",
      ]),
    ]),
    sec("3.3", "Fundamental Analysis", [
      sub("trading", "3.3", "1", "Forex Fundamentals", [
        "Central bank policy / forward guidance",
        "GDP",
        "Inflation: CPI, PPI",
        "Employment: NFP, unemployment",
        "Retail Sales",
        "Manufacturing / Services PMI",
        "Trade balance / current account",
        "Economic calendar reading",
        "Track Fed, ECB, BoE, BoJ, RBA, SNB, BoC",
        "Geopolitical events",
        "Currency correlations",
      ]),
      sub("trading", "3.3", "2", "Equity Fundamentals", [
        "Income Statement",
        "Balance Sheet",
        "Cash Flow Statement",
        "P/E ratio",
        "P/B ratio",
        "EV/EBITDA",
        "Dividend yield / payout",
        "PEG ratio",
        "Industry dynamics",
        "Porter's Five Forces",
        "SWOT for companies",
        "Management quality assessment",
        "Earnings calls and annual reports",
        "NSE companies / CDSC portal",
      ]),
    ]),
    sec("3.4", "Trading Psychology", [
      sub("trading", "3.4", "1", "The Mental Game", [
        "Why most traders fail",
        "Psychological cycle of a losing trader",
        "FOMO neutralization",
        "Revenge trading",
        "Overconfidence after winning streaks",
        "Loss aversion distortion",
        "Role of ego in trading",
      ]),
      sub("trading", "3.4", "2", "Disciplined Mindset", [
        "Process vs outcome thinking",
        "Detachment from individual trades",
        "Emotional neutrality",
        "Journaling as performance tool",
        "Meditation and mindfulness",
        "Books: Trading in the Zone, The Disciplined Trader",
      ]),
      sub("trading", "3.4", "3", "Trading Journal", [
        "Setup type and rationale",
        "Entry, stop loss, take profit",
        "Emotional state before/after",
        "Outcome and review",
        "Weekly / monthly performance reviews",
        "Pattern analysis: most profitable setups",
        "Building trading statistics",
      ]),
    ]),
    sec("3.5", "Risk Management", [
      sub("trading", "3.5", "1", "Core Principles", [
        "Never risk more than 1-2% per trade",
        "Fixed fractional position sizing",
        "Kelly Criterion (theory)",
        "Risk/Reward minimum 1:2",
        "Max daily drawdown limits",
        "Max weekly drawdown limits",
        "Circuit breaker approach",
      ]),
      sub("trading", "3.5", "2", "Trade Execution", [
        "Market vs limit vs stop orders",
        "Calculating lot sizes (forex)",
        "Stop losses: technical vs percentage",
        "Take profit strategies",
        "Partial profit taking",
        "Break-even stop management",
      ]),
      sub("trading", "3.5", "3", "Portfolio-Level Risk", [
        "Correlation between open positions",
        "Total portfolio exposure",
        "Diversification across pairs/stocks",
        "Hedging strategies",
      ]),
    ]),
    sec("3.6", "Trading Systems & Strategy", [
      sub("trading", "3.6", "1", "Building a System", [
        "Market selection",
        "Timeframe selection",
        "Entry trigger",
        "Stop loss placement rule",
        "Take profit rule",
        "Trade management rules",
        "Exit rules",
        "Backtesting on historical data",
        "Forward testing on demo",
        "Win rate + RR for profitability",
        "Expectancy formula",
      ]),
      sub("trading", "3.6", "2", "Data Science Edge", [
        "Backtesting in Python (Backtrader, Zipline, VectorBT)",
        "Quantitative strategy development",
        "Feature engineering from OHLCV",
        "Classification models for direction",
        "Avoiding overfitting in financial ML",
        "Sentiment analysis from news/social",
        "Statistical arbitrage concepts",
        "Building a live trading bot",
      ]),
      sub("trading", "3.6", "3", "Brokers & Platforms", [
        "Choosing a regulated broker (CMA Kenya)",
        "MT4 / MT5 mastery",
        "TradingView for charting",
        "Broker fees: spread, commission, swap",
        "Funded accounts (FTMO model — pros/cons)",
      ]),
    ]),
    sec("3.7", "Equity Trading — NSE", [
      sub("trading", "3.7", "1", "Trading the NSE", [
        "Opening a CDS account",
        "Using NSE-approved brokers",
        "NSE trading hours and settlement",
        "T+3 settlement cycle",
        "Reading the NSE daily report",
      ]),
      sub("trading", "3.7", "2", "NSE Stocks Worth Studying", [
        "Safaricom (SCOM) — M-Pesa data plays",
        "Equity Group (EQTY) — regional banking",
        "KCB Group (KCB) — government relationships",
        "EABL — consumer defensive",
        "Bamburi Cement (BAMB) — real estate cycle",
        "Co-operative Bank (COOP)",
        "Stanbic Holdings",
      ]),
    ]),
  ]
);

// ============ SKILL 1: SALES ============
const sales = c(
  "sales",
  "Skill 1",
  "skill",
  "Sales",
  "Most transferable skill. Underpins everything.",
  "Sales is the most transferable skill you will ever build. It underpins your real estate agency, your consulting practice, your trading fundraising, and every negotiation you will ever have. The world runs on sales.",
  [
    sec("4.1", "Sales Fundamentals", [
      sub("sales", "4.1", "1", "The Sales Mindset", [
        "Reframing sales: service, not manipulation",
        "Buyer psychology",
        "Belief in what you sell",
        "Rejection as data, not failure",
        "Push vs pull selling",
      ]),
      sub("sales", "4.1", "2", "The Sales Process", [
        "Prospecting: ICP",
        "Inbound vs outbound",
        "Cold outreach: email, LinkedIn, phone, WhatsApp",
        "Referral systems",
        "BANT framework",
        "MEDDIC framework",
        "Qualifying questions that don't interrogate",
        "Active listening",
        "Open-ended questioning",
        "Pain point identification",
        "SPIN Selling method",
        "FAB framework",
        "Tailoring presentations",
        "Storytelling in presentations",
        "Feel-felt-found method",
        "Price objections",
        "Timing objections",
        "Trust objections",
        "Assumptive close",
        "Summary close",
        "Trial close",
        "Creating urgency ethically",
        "Follow-up sequences",
        "Value-adding touchpoints",
      ]),
    ]),
    sec("4.2", "Advanced Sales Skills", [
      sub("sales", "4.2", "1", "Consultative Selling", [
        "Becoming a trusted advisor",
        "Solution vs product selling",
        "Long-term client relationships",
        "Account management and upselling",
      ]),
      sub("sales", "4.2", "2", "Real Estate Sales", [
        "Emotional selling",
        "Price-too-high objection",
        "Let-me-think-about-it objection",
        "I-want-more-options objection",
        "Market-might-drop objection",
        "Creating urgency on property deals",
        "Pitching investors vs end-users",
      ]),
      sub("sales", "4.2", "3", "Sales for Consulting", [
        "Selling complex/intangible services",
        "Proposal/SOW as a sales tool",
        "Pricing strategy and anchoring",
        "References and social proof",
        "Sales pipeline for consulting",
      ]),
    ]),
    sec("4.3", "Tools & Systems", [
      sub("sales", "4.3", "1", "Stack", [
        "CRM mastery: HubSpot, Salesforce, Zoho",
        "Email sequences and automation",
        "LinkedIn Sales Navigator",
        "Cold email tools: Apollo, Lemlist",
        "Metrics: conversion, pipeline velocity, win rates",
      ]),
    ]),
    sec("4.4", "Books & Resources", [
      sub("sales", "4.4", "1", "Reading List", [
        "SPIN Selling — Neil Rackham",
        "The Challenger Sale — Matthew Dixon",
        "Never Split the Difference — Chris Voss",
        "How to Win Friends and Influence People — Carnegie",
        "Sell or Be Sold — Grant Cardone",
        "$100M Offers — Alex Hormozi",
      ]),
    ]),
  ]
);

// ============ SKILL 2: NEGOTIATION ============
const negotiation = c(
  "negotiation",
  "Skill 2",
  "skill",
  "Negotiation",
  "Highest ROI skill. Every dollar saved is earned.",
  "Every dollar you don't negotiate away is a dollar earned. In real estate alone, strong negotiation can save or earn you millions per deal. One of the highest ROI skills you can ever develop.",
  [
    sec("5.1", "Negotiation Fundamentals", [
      sub("negotiation", "5.1", "1", "Core Concepts", [
        "BATNA",
        "ZOPA",
        "Reservation point (walk-away)",
        "Anchoring",
        "Distributive vs integrative",
        "Win-win vs win-lose strategies",
      ]),
      sub("negotiation", "5.1", "2", "Tactical Skills", [
        "The power of silence",
        "Mirroring and labeling",
        "Tactical empathy",
        "Calibrated questions (how, what, why)",
        "Ackerman bargaining model",
        "Flinching",
        "Good cop / bad cop",
        "The nibble technique",
        "Deadline pressure",
      ]),
    ]),
    sec("5.2", "Negotiation Contexts", [
      sub("negotiation", "5.2", "1", "Real Estate", [
        "Property purchase price",
        "Buyer's agent",
        "Listing agent",
        "Lease: rent, deposit, terms",
        "Developers / off-plan sellers",
        "Cross-cultural dynamics in Kenya",
      ]),
      sub("negotiation", "5.2", "2", "Business & Consulting", [
        "Consulting fees",
        "Partnership / JV negotiation",
        "Employment & compensation",
        "Vendor / supplier negotiation",
      ]),
    ]),
    sec("5.3", "Books & Resources", [
      sub("negotiation", "5.3", "1", "Reading List", [
        "Never Split the Difference — Chris Voss",
        "Getting to Yes — Fisher, Ury & Patton",
        "Negotiation Genius — Deepak Malhotra",
        "The Art of Negotiation — Michael Wheeler",
      ]),
    ]),
  ]
);

// ============ SKILL 3: PUBLIC SPEAKING ============
const speaking = c(
  "public-speaking",
  "Skill 3",
  "skill",
  "Public Speaking",
  "The multiplier skill. Command rooms, scale ideas.",
  "Public speaking is the multiplier skill. Once you can command a room, your ideas travel further, your clients trust you faster, your deals close more easily, and your brand grows without advertising. The direct upgrade of every other skill you have.",
  [
    sec("6.1", "Fundamentals", [
      sub("public-speaking", "6.1", "1", "Voice & Delivery", [
        "Vocal variety: pitch, pace, volume, tone",
        "Eliminating filler words",
        "Projection and diaphragmatic breathing",
        "Pausing for effect",
        "Enunciation and clarity",
        "Recording yourself for practice",
      ]),
      sub("public-speaking", "6.1", "2", "Body Language", [
        "Eye contact",
        "Posture and stage presence",
        "Hand gestures that reinforce meaning",
        "Stage movement vs standing still",
        "Eliminating nervous habits",
      ]),
      sub("public-speaking", "6.1", "3", "Structure & Content", [
        "Rule of three",
        "Opening hooks (shock, story, question, stat)",
        "Building to a peak",
        "Memorable closings",
        "Hero's journey structure",
        "Problem-Agitate-Solution",
        "Setup, conflict, resolution",
      ]),
    ]),
    sec("6.2", "Types of Speaking", [
      sub("public-speaking", "6.2", "1", "Presentations", [
        "Client presentations for consulting",
        "Investor pitches",
        "Real estate property presentations",
        "Data storytelling for non-technical audiences",
      ]),
      sub("public-speaking", "6.2", "2", "Networking & Social", [
        "30-second introductions",
        "Conversation leadership",
        "Panel discussions and Q&A",
      ]),
      sub("public-speaking", "6.2", "3", "Content Creation", [
        "YouTube / video delivery",
        "Podcast appearances",
        "Webinars and online courses",
      ]),
    ]),
    sec("6.3", "How to Practice", [
      sub("public-speaking", "6.3", "1", "Practice Plan", [
        "Join Toastmasters Nairobi",
        "Record a 2-minute video weekly",
        "Speak at every opportunity",
        "Take every presentation, even small ones",
      ]),
    ]),
    sec("6.4", "Books & Resources", [
      sub("public-speaking", "6.4", "1", "Reading List", [
        "Talk Like TED — Carmine Gallo",
        "The Art of Public Speaking — Dale Carnegie",
        "Steal the Show — Michael Port",
        "Speak to Win — Brian Tracy",
      ]),
    ]),
  ]
);

// ============ SKILL 4: LAW ============
const law = c(
  "law",
  "Skill 4",
  "skill",
  "Law (Real Estate & Contract Focus)",
  "Protect yourself, structure deals, know when to call a lawyer.",
  "You don't need a law degree. You need enough legal knowledge to protect yourself, structure deals correctly, and know when to bring in a lawyer. One of the most financially protective skills you will ever develop.",
  [
    sec("7.1", "Contract Law", [
      sub("law", "7.1", "1", "Elements of a Valid Contract", [
        "Offer and acceptance",
        "Consideration",
        "Capacity to contract",
        "Legality of purpose",
        "Consensus ad idem",
      ]),
      sub("law", "7.1", "2", "Contract Types", [
        "Sale agreements (property)",
        "Lease and tenancy agreements",
        "Service agreements (consulting)",
        "NDAs",
        "MOUs",
        "JV agreements",
        "Employment contracts",
        "Agency agreements",
      ]),
      sub("law", "7.1", "3", "Reading & Interpreting", [
        "Key clauses: payment, delivery, termination, liability",
        "Force majeure",
        "Indemnification & limitation of liability",
        "Arbitration vs litigation",
        "Governing law / jurisdiction",
        "Red flags in any contract",
      ]),
    ]),
    sec("7.2", "Kenyan Property Law", [
      sub("law", "7.2", "1", "Key Statutes", [
        "Land Act 2012",
        "Land Registration Act 2012",
        "Stamp Duty Act",
        "Rent Restriction Act",
        "Physical and Land Use Planning Act 2019",
        "EMCA",
        "Sectional Properties Act 2020",
        "Eviction procedures under Kenyan law",
      ]),
    ]),
    sec("7.3", "Business Law", [
      sub("law", "7.3", "1", "Business Structures", [
        "Sole proprietorship",
        "Partnerships (general & limited)",
        "Limited Liability Companies (Ltd)",
        "Company registration via eCitizen",
        "Private vs public companies",
      ]),
      sub("law", "7.3", "2", "Intellectual Property", [
        "Copyright basics",
        "Trademarks (KIPI)",
        "Patents",
        "Trade secrets / confidentiality",
      ]),
      sub("law", "7.3", "3", "Tax Law Basics", [
        "KRA PIN registration",
        "Income tax: individual & corporate",
        "VAT: thresholds and filing",
        "Capital gains tax",
        "Withholding tax",
        "iTax compliance",
      ]),
    ]),
    sec("7.4", "Using Lawyers Effectively", [
      sub("law", "7.4", "1", "Working With Counsel", [
        "When to hire vs DIY",
        "How to brief a lawyer",
        "Understanding legal invoices",
        "Long-term relationship with an advocate",
        "Specialist advocates: conveyancing, commercial, tax",
      ]),
    ]),
  ]
);

// ============ SKILL 5: BUSINESS MGMT ============
const business = c(
  "business",
  "Skill 5",
  "skill",
  "Business Management",
  "OS that runs everything. Converts skills to enterprises.",
  "The operating system that runs everything else. Without business management skills, your three careers will remain freelance hustles rather than scalable enterprises. This converts skills into businesses.",
  [
    sec("8.1", "Strategy & Planning", [
      sub("business", "8.1", "1", "Strategic Thinking", [
        "Vision, mission, values",
        "Personal brand strategy",
        "Competitive analysis",
        "Blue Ocean vs Red Ocean",
        "Porter's Generic Strategies",
        "SWOT for your ventures",
        "PESTLE analysis",
      ]),
      sub("business", "8.1", "2", "Business Planning", [
        "Business model canvas",
        "Value proposition design",
        "Revenue models: transaction, subscription, licensing, consulting",
        "Writing a business plan",
        "OKRs",
        "KPI identification and tracking",
      ]),
    ]),
    sec("8.2", "Finance & Accounting", [
      sub("business", "8.2", "1", "Financial Literacy", [
        "Reading a P&L",
        "Reading a Balance Sheet",
        "Reading a Cash Flow statement",
        "Profit vs cash flow",
        "Gross vs net margin",
        "EBITDA and valuation",
      ]),
      sub("business", "8.2", "2", "Financial Management", [
        "Separating personal & business finances",
        "Business bank account",
        "Bookkeeping / double-entry",
        "QuickBooks, Xero, Sage",
        "Invoicing & accounts receivable",
        "Expense management & accounts payable",
        "Monthly financial review habit",
      ]),
      sub("business", "8.2", "3", "Pricing & Revenue", [
        "Cost-plus pricing",
        "Value-based pricing",
        "Competitive pricing",
        "Psychological pricing",
        "When and how to raise prices",
        "Recurring revenue streams",
      ]),
      sub("business", "8.2", "4", "Fundraising & Capital", [
        "Bootstrapping",
        "Debt vs equity",
        "Angel investors",
        "VC stages: pre-seed, seed, Series A",
        "Pitch deck structure",
        "Valuation methods",
        "Kenya: KEPSA, bank SME loans, Saccos",
      ]),
    ]),
    sec("8.3", "Operations & Systems", [
      sub("business", "8.3", "1", "Building Systems", [
        "SOPs — documenting everything",
        "Process mapping and optimization",
        "Automation priorities",
        "Agile, Waterfall, Kanban",
        "Tools: Notion, Asana, Trello, Monday",
      ]),
      sub("business", "8.3", "2", "Time & Productivity", [
        "Time blocking for multiple careers",
        "Eisenhower Matrix",
        "Deep vs shallow work (Cal Newport)",
        "Energy management",
        "Weekly reviews and planning rituals",
        "Saying no strategically",
      ]),
      sub("business", "8.3", "3", "Technology & Tools", [
        "G Suite / Microsoft 365",
        "Document management systems",
        "Slack / Teams",
        "Cloud storage and file org",
        "Password management & cybersecurity basics",
      ]),
    ]),
    sec("8.4", "People & Leadership", [
      sub("business", "8.4", "1", "Hiring & Team", [
        "Writing job descriptions",
        "Interviewing & evaluation",
        "Onboarding design",
        "Performance management",
        "Contractors vs employees",
        "Building remote teams",
      ]),
      sub("business", "8.4", "2", "Leadership", [
        "Styles: transformational, servant, situational",
        "Delegation",
        "Giving / receiving feedback",
        "Conflict resolution",
        "Team culture",
        "Motivating beyond money",
      ]),
      sub("business", "8.4", "3", "Networking", [
        "Building a strategic network",
        "Give before you take",
        "LinkedIn for relationships",
        "Industry events in Kenya",
        "Mentorship: finding & being one",
      ]),
    ]),
    sec("8.5", "Marketing & Branding", [
      sub("business", "8.5", "1", "Personal Brand", [
        "Niche & expertise positioning",
        "Content strategy (LinkedIn, X, YouTube)",
        "Thought leadership writing",
        "Speaking at events as brand builder",
        "Digital footprint: site, portfolio, case studies",
      ]),
      sub("business", "8.5", "2", "Digital Marketing", [
        "SEO basics",
        "Content marketing: blogs, newsletters, podcasts",
        "Social media for professional services",
        "Email marketing",
        "Paid ads: Meta, Google, LinkedIn",
        "Analytics: GA, Meta Business Suite",
      ]),
      sub("business", "8.5", "3", "Business Development", [
        "Partnership opportunities",
        "Strategic alliances and JVs",
        "Licensing / white-labeling",
        "Building distribution channels",
      ]),
    ]),
    sec("8.6", "Legal & Compliance", [
      sub("business", "8.6", "1", "Compliance Basics", [
        "Business registration (eCitizen)",
        "Tax compliance obligations",
        "Kenya Data Protection Act 2019",
        "Industry-specific regulations",
        "Insurance: PI and business insurance",
        "IP protection for products",
      ]),
    ]),
    sec("8.7", "Books & Resources", [
      sub("business", "8.7", "1", "Reading List", [
        "The E-Myth Revisited — Michael Gerber",
        "Good to Great — Jim Collins",
        "Zero to One — Peter Thiel",
        "The Lean Startup — Eric Ries",
        "Traction — Gino Wickman",
        "Built to Sell — John Warrillow",
        "The Hard Thing About Hard Things — Ben Horowitz",
        "Thinking Fast and Slow — Daniel Kahneman",
      ]),
    ]),
  ]
);

export const CATEGORIES: Category[] = [
  dataScience,
  realEstate,
  trading,
  sales,
  negotiation,
  speaking,
  law,
  business,
];

export const getCategory = (slug: string) => CATEGORIES.find((c) => c.slug === slug);
